[package]
name = "gacha_builder"
version = "0.1.0"
edition = "2021"

[dependencies]
figment = { version = "0.10.13", features = ["toml"] }
rocket = "0.5.0"
rocket_db_pools = { version = "0.1.0", features = ["diesel_postgres"]}
serde = { version = "1.0.194", features = ["derive"] }
